### ISSUE TITLE
Add configuration or ability to format nodes inside SELECT from new line

### ISSUE THREAD

**Issue by antonzhyliuk** [jamis/sqlpp#1]
Now tool works like:

``` sql
SELECT attr1, attr2, attr3
FROM (
  blabla
) bla
WHERE ...
```

It will be very pleasant to have ability for formatting nodes inside select as:

``` sql
SELECT attr1,
       attr2,
       attr3
FROM (
  blabla
) bla
WHERE ...
```

**Comment by jamis** [comment]
Fixed in 9bb4809036709970507e219dfb807b5969bcfb7e. I'd been meaning to add this, thanks for the nudge. :)
